import { useRef, useState, type ChangeEvent } from 'react'
import { importInventoryForLayout } from '../domain/inventoryImportV2'
import type { WarehouseLocation } from '../domain/warehouse'
import type { ImportSummary } from '../store/digitalTwinStore'

export function ImportPanel({skeleton,onImport,onRestore,dataSource,summary}:{skeleton:WarehouseLocation[];onImport:(locations:WarehouseLocation[],summary:ImportSummary)=>void;onRestore:()=>void;dataSource:'demo'|'csv'|'manual';summary:ImportSummary|null}){
 const inputRef=useRef<HTMLInputElement | null>(null);const [feedback,setFeedback]=useState('')
 async function handleFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;if(!file.name.toLocaleLowerCase('pt-BR').endsWith('.csv')){setFeedback('Envie um arquivo CSV.');return}try{const result=importInventoryForLayout(await file.text(),skeleton);if(result.importedRows===0){setFeedback(result.issues[0]?.message??'Nenhuma linha válida encontrada.');return}onImport(result.locations,{fileName:file.name,rowsRead:result.rowsRead,importedRows:result.importedRows,issueCount:result.issues.length});setFeedback(`${result.importedRows} linha(s) aplicadas. ${result.issues.length} inconsistência(s) identificada(s).`)}catch{setFeedback('Não foi possível ler o arquivo.') }}
 function downloadTemplate(){const sample=skeleton.slice(0,12).map((location,index)=>`${location.address},${10001+(index%5)},Produto exemplo ${index+1},${index%3===0?0:80},100,L${2000+index},PLT-${String(index+1).padStart(5,'0')},2027-12-15,${index%3===0?'vazio':'ocupado'},sistema,`).join('\n');const csv=`endereco,sku,descricao,quantidade,capacidade,lote,pallet,validade,status,confirmacao,ultima_conferencia\n${sample}`;const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='modelo-estoque-cd-digital.csv';anchor.click();URL.revokeObjectURL(url)}
 return<section className="panel-section"><div className="section-heading"><div><span className="eyebrow">Integração de dados</span><h2>Importar estoque</h2></div></div><p className="muted">O arquivo atualiza somente endereços existentes no layout ativo. Linhas inválidas são rejeitadas e contabilizadas.</p><div className="import-status"><strong>{dataSource==='csv'?'Base importada':dataSource==='manual'?'Layout configurado':'Cenário demonstrativo'}</strong>{summary&&<span>{summary.fileName} · {summary.importedRows}/{summary.rowsRead} linhas · {summary.issueCount} inconsistências</span>}</div><input ref={inputRef} className="hidden-input" type="file" accept=".csv,text/csv" onChange={handleFile}/><div className="action-stack"><button type="button" className="primary" onClick={()=>inputRef.current?.click()}>Selecionar CSV</button><button type="button" className="secondary" onClick={downloadTemplate}>Baixar modelo do layout atual</button><button type="button" className="danger-link" onClick={onRestore}>Restaurar demonstração</button></div>{feedback&&<div className="feedback">{feedback}</div>}<div className="truth-box"><strong>Regra de confiança</strong><p>Importar uma linha registra o estado informado pelo sistema. A posição só recebe confirmação física após contagem ou movimentação confirmada pelo operador.</p></div></section>
}
